package com.store_me.storeme.ui.main

const val USER_HOME = "USER_HOME"
const val FAVORITE = "FAVORITE"
const val NEAR_PLACE = "NEAR_PLACE"
const val STORE_TALK = "STORE_TALK"
const val MY_MENU = "MY_MENU"

/**
 * USER_HOME = 0
 * FAVORITE = 1
 * NEAR_PLACE = 2
 * STORE_TALK = 3
 * PROFILE = 4
 */
val CUSTOMER_BOTTOM_ITEM_LIST = listOf(USER_HOME, FAVORITE, NEAR_PLACE, STORE_TALK, MY_MENU)

const val OWNER_HOME = "OWNER_HOME"
const val CUSTOMER_MANAGEMENT = "CUSTOMER_MANAGEMENT"
const val OWNER_ADD = "OWNER_ADD"
const val STORE_INFO = "STORE_INFO"

/**
 * OWNER_HOME = 0
 * CUSTOMER_MANAGEMENT = 1
 * OWNER_ADD = 2
 * STORE_TALK = 3
 * STORE_INFO = 4
 */
val OWNER_BOTTOM_ITEM_LIST = listOf(OWNER_HOME, CUSTOMER_MANAGEMENT, OWNER_ADD, STORE_TALK, STORE_INFO)